apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mandi-to-market-ingress
  labels:
    app: mandi-to-market
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mandi-to-market-service
                port:
                  number: 80
